[package]
name = "ggsnap"
version = "0.1.0"
authors = ["Marcus Pedersén <marcus.pedersen@slu.se>"]

[dependencies]
chrono = "0.4"
clap = "2.29.4"
regex = "0.2"
#snapurd_util = { path = "../snapurd_util" }